config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  resources :users, only: [:show]

  resources :addresses, only: [:new, :create, :edit, :update]

  resources :credit_cards, only: [:new, :create] do
    collection do
      post 'delete', to: 'credit_cards#delete'
    end 
  end


  resources :products do
    resources :purchases, only: [:show] do
      collection do
        post 'pay', to: 'purchases#pay'
      end
    collection do
      get 'search'
    end
  end
end

  root 'products#index'

end

app/models/address.rb
class Address < ApplicationRecord
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  
  
  belongs_to :user, optional: true

  validates :first_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
  validates :last_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
  validates :first_name_kana, presence: true, format: { with: /\A[ぁ-んー－]+\z/ }
  validates :last_name_kana, presence: true, format: { with: /\A[ぁ-んー－]+\z/ }
  validates :postal_code, presence: true, format: { with: /\A\d{3}[-]\d{4}\z/ }
  validates :prefecture, presence: true 
  validates :city, presence: true
  validates :address, presence: true 
  validates :tel, allow_blank: true, format: { with: /\A\d{10,11}\z/ }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end
# test

app/models/brand.rb
class Brand < ActiveHash::Base
  self.data = [
      {id: 1, name: 'NIKE'}, {id: 2, name: 'adidas'}, {id: 3, name: 'asics'},
      {id: 4, name: 'mizuno'}, {id: 5, name: 'umbro'}, {id: 6, name: 'puma'}
  ]
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
      {id: 1, name: 'レディース'}, {id: 2, name: 'メンズ'}, {id: 3, name: 'ベビー・キッズ'},
      {id: 4, name: 'インテリア'}, {id: 5, name: '本'}, {id: 6, name: 'ホビー'},
      {id: 7, name: 'コスメ・美容'}, {id: 8, name: '家電'}, {id: 9, name: 'スポーツ・レジャー'},
      {id: 10, name: 'ハンドメイド'}, {id: 11, name: 'チケット'}, {id: 12, name: 'その他'},
  ]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user

  validates :customer_id, presence: true
  validates :user_id, presence: true
  validates :card_token, presence: true
end

app/models/delivery.rb
class Delivery < ActiveHash::Base
  self.data = [
      {id: 1, name: '送料込'}, {id: 2, name: '着払い'}
  ]
end

app/models/deliverytime.rb
class  Deliverytime < ActiveHash::Base
  self.data = [
      {id: 1, name: '1〜2日で発送'}, {id: 2, name: '3〜4日で発送'}, {id: 3, name: '5〜7日で発送'}
  ]
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :product
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :product
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  def self.search(search)
    Product.where('name LIKE(?)', "%#{search}%")
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :brand
  belongs_to_active_hash :status
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :size
  belongs_to_active_hash :deliverytime
  belongs_to_active_hash :delivery
  

  validates :name, presence: true
  validates :user_id, presence: true
  validates :price, presence: true
  validates :text, presence: true
  validates :category_id, presence: true
  validates :brand_id, presence: true
  validates :status_id, presence: true
  validates :prefecture_id, presence: true
  validates :size_id, presence: true
  validates :delivery_id, presence: true
  validates :deliverytime_id, presence: true

end

app/models/size.rb
class  Size < ActiveHash::Base
  self.data = [
      {id: 1, name: 'XS'}, {id: 2, name: 'S'}, {id: 3, name: 'M'},
      {id: 4, name: 'L'}, {id: 5, name: 'XL'}, {id: 6, name: 'XXL'}
  ]
end

app/models/status.rb
class  Status < ActiveHash::Base
  self.data = [
      {id: 1, name: '新品・未使用'}, {id: 2, name: '未使用に近い'}, {id: 3, name: '傷汚れなし'},
      {id: 4, name: 'やや傷汚れあり'}, {id: 5, name: '傷汚れあり'}, {id: 6, name: '全体的に状態が悪い'}
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         


      has_many :commnets
      has_many :products
      has_many :likes_product, through: :likes, source: :product
      has_many :comments, dependent: :destroy
      has_many :likes, dependent: :destroy
      has_many :products, dependent: :destroy
      has_many :credit_cards, dependent: :destroy
      has_one :address, dependent: :destroy         


      VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

      validates :nickname, presence: true
      validates :email, presence: true, uniqueness: true, format:{with: VALID_EMAIL}
      validates :password, presence: true, confirmation: true, length: { minimum: 7 }
      validates :first_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
      validates :last_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
      validates :first_name_kana, presence: true, format: { with: /\A[ぁ-んー－]+\z/ }
      validates :last_name_kana, presence: true, format: { with: /\A[ぁ-んー－]+\z/ } 
      validates :birthday, presence: true, length: { is: 8 }, format: { with: /\A[0-9]+\z/ }

end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  require 'payjp'

  def new
    card = CreditCard.find_by(user_id: current_user.id)
  end

  def create
    Payjp.api_key = ENV["PAYJP_ACCESS_KEY"]
    if params['payjp-token'].blank?
      flash[:alert] = "入力に誤りがあります。もう一度入力してください。"
      redirect_to new_credit_card_path
    else
      customer = Payjp::Customer.create(card: params['payjp-token'])
      @card = CreditCard.new(user_id: current_user.id, customer_id: customer.id, card_token: customer.default_card)
      if @card.save
        flash[:notice] = "クレジットカード情報を登録しました。"
        redirect_to root_path and return
      else
        flash[:alert] = "入力に誤りがあります。もう一度入力してください。"
        redirect_to new_credit_card_path
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    card = CreditCard.find_by(user_id: current_user.id)
    if card.blank?
    else
      Payjp.api_key = ENV["PAYJP_ACCESS_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      flash[:alert] = "クレジットカード情報を削除しました"
      redirect_to user_path(current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    if CreditCard.find_by(user_id: current_user.id).present?
      @card = CreditCard.find_by(user_id: current_user.id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/credit_cards/new.html.haml
.header
  .header_search
    .header_search_logo
      = image_tag '/material/logo/logo.png', class: "header_search_logo"
  .notifications
    %span
      = render 'layouts/notifications'

.new_card
  .new_card_user
    ログインユーザー名
    %br/
    %span
      = current_user.nickname

  = form_tag(credit_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
    .new_card_form   
      %label カード番号
      = text_field_tag "number", "", class: "new_card_form_text", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
      %br
      %label 有効期限(month)
      %select#exp_month{name: "exp_month", type: "text", class: "new_card_form_text"}
        %option{value: ""} --
        %option{value: "1"}01
        %option{value: "2"}02
        %option{value: "3"}03
        %option{value: "4"}04
        %option{value: "5"}05
        %option{value: "6"}06
        %option{value: "7"}07
        %option{value: "8"}08
        %option{value: "9"}09
        %option{value: "10"}10
        %option{value: "11"}11
        %option{value: "12"}12
      %label 有効期限(year)
      %select#exp_year{name: "exp_year", type: "text", class: "new_card_form_text"}
        %option{value: ""} --
        %option{value: "2019"}19
        %option{value: "2020"}20
        %option{value: "2021"}21
        %option{value: "2022"}22
        %option{value: "2023"}23
        %option{value: "2024"}24
        %option{value: "2025"}25
        %option{value: "2026"}26
        %option{value: "2027"}27
        %option{value: "2028"}28
        %option{value: "2029"}29
      %br
      %label セキュリティコード
      = text_field_tag "cvc", "", class: "cvc new_card_form_text", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
      #card_token
      = submit_tag "クレジットカードを登録する", id: "token_submit"
  
  

app/views/credit_cards/show.html.haml
%label 登録クレジットカード情報
%br
= "**** **** **** " + @default_card_information.last4
%br
- exp_month = @default_card_information.exp_month.to_s
- exp_year = @default_card_information.exp_year.to_s.slice(2,3)
= exp_month + " / " + exp_year
= form_tag(card_delete_path, method: :post, id: 'charge-form',  name: "inputForm") do
  %input{ type: "hidden", name: "card_id", value: "" }
  %button 削除する