config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  resources :users, only: [:show]

  resources :addresses, only: [:new, :create, :edit, :update]

  resources :credit_cards, only: [:new, :create] do
    collection do
      post 'delete', to: 'credit_cards#delete'
    end 
  end


  resources :products do
    resources :purchases, only: [:show] do
      collection do
        post 'pay', to: 'purchases#pay'
      end
    collection do
      get 'search'
    end
  end
end

  root 'products#index'

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  require 'payjp'

  before_action :set_product, only: [:show, :pay]

  def show
    if user_signed_in?
      card = CreditCard.find_by(user_id: current_user.id)
    else
      flash[:alert] = "商品を購入するにはログインしてください"
      redirect_to root_path and return
    end

    if card.blank?
      #登録された情報がない場合にカード登録画面に移動
      redirect_to new_credit_card_path
      flash[:alert] = "商品を購入するにはクレジットカードの登録をしてください。" 
    else
      Payjp.api_key = ENV["PAYJP_ACCESS_KEY"]
      #保管した顧客IDでpayjpから情報取得
      customer = Payjp::Customer.retrieve(card.customer_id)
      #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
      @default_card_information = customer.cards.retrieve(card.card_token)
    end

  end



  def pay
    if @product.buy_user_id.present?
      flash[:alert] = "商品は既に購入されています"
      redirect_to root_path and return
    end
    
    card = CreditCard.find_by(user_id: current_user.id)
    Payjp.api_key = ENV["PAYJP_ACCESS_KEY"]
    Payjp::Charge.create(
      amount: @product.price, # 決済する値段
      card: params['payjp-token'], # フォームを送信すると生成されるトークン
      customer: card.customer_id, #顧客ID
      currency: 'jpy', #日本円
    )
    @product.update(buy_user_id: current_user.id)
    redirect_to root_path
    flash[:notice] = "商品の購入が完了しました"
  end

  private
  def purchase_params
    params.require(:product).merge(buy_user_id: current_user.id)
  end

  def set_product
    @product = Product.find(params[:product_id])
  end

end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/show.html.haml
.show_header
  .show_header_search
    .show_header_search_logo
      = image_tag '/material/logo/logo.png', class: "show_header_search_logo"

.card
  .card_purchace
    .card_purchace_main
      .card_purchace_images  
        = image_tag @product.images[0].image.url, class: "card_purchace_image"
      .card_purchace_name
        = @product.name
        .card_purchace_price
          ￥
          = @product.price
          %span.card_purchace_price_delivery
            = @product.delivery.name
          %span
            (税込み)
    
    .card_purchace_main_prefecture
      .card_purchace_main_prefecture_title
        配送先住所
      .card_purchace_main_prefecture_content
        .card_purchace_main_prefecture_content_postal
          〒
          = current_user.address.postal_code
        .card_purchace_main_prefecture_content_address
          = current_user.address.prefecture.name
          = current_user.address.city
          = current_user.address.address
          = current_user.address.apartment
        .card_purchace_main_prefecture_content_name
          = current_user.last_name
          = current_user.first_name
    
    .card_buy
      - if @default_card_information.blank?
        %br/
      - else
        %span
          支払いカード情報
        %br/
        .card_buy_option
          = "**** **** **** " + @default_card_information.last4 + "/"
          - exp_month = @default_card_information.exp_month.to_s
          - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
          有効期限
          = exp_month + " / " + exp_year
        %br/
      .card_buy_submit
        = link_to pay_product_purchases_path, method: :post, class: "card_buy_submit_button" do
          購入する