config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  resources :users, only: [:show]

  resources :addresses, only: [:new, :create, :edit, :update]

  resources :credit_cards, only: [:new, :create] do
    collection do
      post 'delete', to: 'credit_cards#delete'
    end 
  end


  resources :products do
    resources :purchases, only: [:show] do
      collection do
        post 'pay', to: 'purchases#pay'
      end
    collection do
      get 'search'
    end
  end
end

  root 'products#index'

end

app/models/product.rb
class Product < ApplicationRecord

  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  def self.search(search)
    Product.where('name LIKE(?)', "%#{search}%")
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :brand
  belongs_to_active_hash :status
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :size
  belongs_to_active_hash :deliverytime
  belongs_to_active_hash :delivery
  

  validates :name, presence: true
  validates :user_id, presence: true
  validates :price, presence: true
  validates :text, presence: true
  validates :category_id, presence: true
  validates :brand_id, presence: true
  validates :status_id, presence: true
  validates :prefecture_id, presence: true
  validates :size_id, presence: true
  validates :delivery_id, presence: true
  validates :deliverytime_id, presence: true

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @categories = Category.all
    @products = Product.includes(:images).order('created_at DESC').limit(4)
  end

  def new
    if user_signed_in?
      @product = Product.new
      @product.images.new
    else
      flash[:alert] = "商品を出品するにはログインしてください。"
      redirect_to root_path and return
    end
    
  end

  def create
    @product = Product.new(product_params)
    unless @product.valid?
      flash[:alert] = "入力に誤りがあります。もう一度入力してください。"
      redirect_to action: :new and return
    end
    @product.save
    redirect_to root_path
    flash[:notice]= "商品を出品しました。"
  end

  def show
    @product = Product.find(params[:id])
    @user = User.find_by(id: @product.user_id)

  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to root_path
    flash[:notice]= "商品を編集しました。"
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to root_path
    flash[:notice]= "商品を削除しました。"
  end



  # def search
  #   @products = Product.search(params[:keyword])
  #   respond_to do |format|
  #     format.json
  #   end
  # end

  
  private
  def product_params
    params.require(:product).permit(:name, :price, :text, :status_id, :size_id, :prefecture_id, :delivery_id, :deliverytime_id, :brand_id, :category_id, images_attributes:  [:image, :_destroy, :id]).merge(user_id: current_user.id)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
.form_title
  = image_tag "/material/logo/logo.png", class: "form_title_img"

.form_content
  .notifications
    %span
      = render 'layouts/notifications'
 
  = form_with model: product, local: true do |f|   
    .previews
      - if product.persisted?
        - product.images.each_with_index do |image, i| 
          = image_tag image.image.url, data: { index: i }, width: "120", height: '130', class: "product_img"
    .image_box        
      = f.fields_for :images do |i|
        .file_field_group{data: {index: i.index}}
          .file_field
            = i.label :image do
              = fa_icon 'camera'
              画像選択
              = i.file_field :image, class: "hidden"
          .remove
            削除
        - if product.persisted? 
          = i.check_box :_destroy, data:{ index: i.index }, class: 'hidden-destroy' 

      - if product.persisted?
        .file_field_group{data: {index: product.images.count}}
          .file_field
            %label(for="image")
              = fa_icon 'camera'
              画像選択
              = file_field_tag :image, name: "product[images_attributes][#{product.images.count}][image]", class: "hidden"
          .remove
            削除

    .product_fields  
      .product_field
        = f.label :name, :商品名
        = f.text_field :name, placeholder: "name"

      .product_field
        = f.label :category_id, :カテゴリー
        = f.collection_select :category_id, Category.all, :id, :name, prompt: "選択してください"
        = fa_icon 'chevron-down', class: "product_field_icon"

      .product_field
        = f.label :brand_id, :ブランド
        = f.collection_select :brand_id, Brand.all, :id, :name, prompt: "選択してください"
        = fa_icon 'chevron-down', class: "product_field_icon"
      
      .product_field
        = f.label :status_id, :商品の状態
        = f.collection_select :status_id, Status.all, :id, :name, prompt: "選択してください"
        = fa_icon 'chevron-down', class: "product_field_icon"
      
      .product_field
        = f.label :size_id, :サイズ
        = f.collection_select :size_id, Size.all, :id, :name, prompt: "選択してください"
        = fa_icon 'chevron-down', class: "product_field_icon"
      
      .product_field
        = f.label :text, :商品概要
        = f.text_area :text, placeholder: "商品説明"
      
      .product_field
        = f.label :delivery_id, :配送料の負担
        = f.collection_select :delivery_id, Delivery.all, :id, :name, prompt: "選択してください"
        = fa_icon 'chevron-down', class: "product_field_icon"
      
      .product_field
        = f.label :deliverytime_id, :発送日時
        = f.collection_select :deliverytime_id, Deliverytime.all, :id, :name, prompt: "選択してください"
        = fa_icon 'chevron-down', class: "product_field_icon"
      
      .product_field
        = f.label :prefecture_id, :発送元の地域
        = f.collection_select :prefecture_id, Prefecture.all, :id, :name, prompt: "選択してください"
        = fa_icon 'chevron-down', class: "product_field_icon"
      
      .product_field
        = f.label :price, :値段
        = f.number_field :price, class: "number", placeholder:"￥"
      
      .product_field_submit
        - if product.persisted?
          = f.submit :更新
          .product_field_submit_delete
            = link_to product_path(product.id), method: :delete, class: "product_field_submit_delete" do
              削除
        - else
          = f.submit :出品


    

app/views/products/edit.html.haml
= render 'form', {product:@product}

app/views/products/index.html.haml
.header
  .header_search
    .header_search_logo
      = image_tag '/material/logo/logo.png', class: "header_search_logo"
    .header_search_form
      = form_with url: 'search_products_path', local: true, class:"header_search_form" do |f|
        = f.text_field :keyword, class: "header_search_form_text", placeholder: "商品を探す"
        = f.label :submit do
          = f.submit class: "hidden"
          .header_search_form_submit
            = image_tag "/material/icon/icon-search 1.png", class: "header_search_form_submit_icon"
  
  .notifications
    %span
      = render 'layouts/notifications'

  .header_link
    .header_link_left
      .header_link_left_category
        カテゴリー
        .header_link_left_category_lists
          - @categories.each do |category|
            .header_link_left_category_lists_name
              = category.name
              %br/
      .header_link_left_brand
        ブランド
    
    .header_link_right
      - if user_signed_in?
        .header_link_right_logout
          = link_to "#{current_user.nickname}さん", "/users/#{current_user.id}", class: "header_link_right_logout_name"
          = link_to destroy_user_session_path, method: :delete, class: "header_link_right_logout" do
            ログアウト
      - else
        .header_link_right_login
          = link_to new_user_session_path, class: "header_link_right_login" do
            ログイン
        .header_link_right_signup
          = link_to new_user_registration_path, class: "header_link_right_signup" do
            新規会員登録
      

    
      

.main
  .main_top
    =image_tag '/material/pict/bg-mainVisual-pict_pc.jpg', class: "main_top_img"
    .main_top_appstore
      = image_tag "/material/icon/Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg", class: "main_top_appstore_img"
    .main_top_google
      = image_tag "/material/icon/google-play-badge.png", class: "main_top_google_img"



    .main_top_title
      %h1
        人生を変えるフリマアプリ
      %p
        FURIMAは誰でも簡単に出品・購入できる 
        %br
        フリマアプリです
  
  .main_reason
    .main_reason_title
      FURIMAが選ばれる３つの理由

    %ul.main_reason_lists
      %li.main_reason_list
        .main_reason_list_img
          .main_reason_list_img_num
            1
          = image_tag '/material/pict/pict-reason-01.jpg', class: "main_reason_list_img"
        .main_reason_list_content
          %h1
            %span
              3分
            ですぐに出品
          %p
            スマホで入力するだけで簡単に出品ができる！

      %li.main_reason_list  
        .main_reason_list_img
          .main_reason_list_img_num 
            2
          = image_tag '/material/pict/pict-reason-02.jpg', class: "main_reason_list_img"
        .main_reason_list_content
          %h1
            %span
              シンプル
            で使いやすい
          %p
            めんどくさい入力はなく、検索も購入もスムーズ！

      %li.main_reason_list
        .main_reason_list_img
          .main_reason_list_img_num
            3
          = image_tag '/material/pict/pict-reason-03.jpg', class: "main_reason_list_img"
        .main_reason_list_content
          %h1
            手数料
            %span
              業界最安
          %p
            最大３％でお得に出品＆購入！

  .main_middle
    .main_middle_img
      =image_tag "/material/pict/bg-topMiddleDl-pict.jpg", class: "main_middle_img"  
      .main_middle_img_content
        %h1
          会員数日本一位
        %p
          FURIMAは、フリマアプリで最も人気。
          %br/
          出品・購入回数も業界最多です！
          %br/
          ほしかったあの商品に出会えるかもしれません。
    .main_middle_appstore
      = image_tag "/material/icon/Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg", class: "main_middle_appstore_img"
    .main_middle_google
      = image_tag "/material/icon/google-play-badge.png", class: "main_middle_google_img"

  
  .main_chara
    .main_chara_title
      FURIMAの特徴

    .main_chara_lists
      .main_chara_list
        .main_chara_list_img
          =image_tag "/material/icon/icon-01.png", class: "main_chara_list_img"    
        .main_chara_list_content
          %h1
            簡単に売り買いできる
          %p
            スマホひとつで、いつでもどこでも簡単に出品・購入が可能！

      .main_chara_list
        .main_chara_list_img
          =image_tag "/material/icon/icon-03.png", class: "main_chara_list_img"      
        .main_chara_list_content
          %h1
            売上金は即日振込みに対応
          %p
            午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
        
      .main_chara_list
        .main_chara_list_img  
          =image_tag "/material/icon/icon-02.png", class: "main_chara_list_img"   
        .main_chara_list_content
          %h1
            様々な支払いに対応
          %p
            お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
        

  .main_pickup
    .main_pickup_category
      %h1
        ピックアップカテゴリー
      %p
        新規投稿商品
      .main_pickup_category_lists
        - @products.each do |product|
          .main_pickup_category_list
            = link_to product_path(product.id) do
              .main_pickup_category_list_img
                = image_tag product.images.first.image.url, class: "main_pickup_category_list_img"
              .main_pickup_category_list_name
                = product.name
              .main_pickup_category_list_option
                .main_pickup_category_list_option_price
                  = product.price
                  円
                  %span
                    (税込)
                .main_pickup_category_list_option_likes
                  ❤️10
              -if product.buy_user_id.present?
                .sold_out
                  sold out
        
    
    .main_pickup_brand
      %h1
        ピックアップブランド
      %p
        アーカイバ
      .main_pickup_brand_lists
        - @products.each do |product|
          .main_pickup_brand_list
            = link_to product_path(product.id) do
              .main_pickup_brand_list_img
                =image_tag product.images.first.image.url, class: "main_pickup_brand_list_img"
              .main_pickup_brand_list_name
                = product.name
              .main_pickup_brand_list_option
                .main_pickup_brand_list_option_price
                  = product.price
                  円
                  %span
                    (税込)
                .main_pickup_brand_list_option_likes
                  ❤️10
              -if product.buy_user_id.present?
                .sold_out
                  sold out

    .main_footer
      .main_footer_img
        = image_tag "/material/pict/bg-appBanner-pict.jpg", class: "main_footer_img"
        .main_footer_img_content
          %h1
            だれでもかんたん、人生を変えるフリマアプリ
          %p
            今すぐ無料ダウンロード！
      .main_footer_icon
        .main_footer_icon_appstore
          = image_tag "/material/icon/Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg", class: "main_footer_icon_appstore_img"
        .main_footer_icon_google
          = image_tag "/material/icon/google-play-badge.png", class: "main_footer_icon_google_img"

.footer
  .footer_lists
    .footer_list
      .footer_list_title
        FURIMAについて
      %ul.footer_list_contents
        %li
          会社概要（運営会社）
        %li
          プライバシーポリシー
        %li
          FURIMA利用規約
        %li
          ポイントに関する特約
    
    .footer_list
      .footer_list_title
        FURIMAを見る
      %ul.footer_list_contents
        %li
          カテゴリー一覧
        %li
          ブランド一覧

    .footer_list
      .footer_list_title
        ヘルプ＆ガイド
      %ul.footer_list_contents
        %li
          FURIMAガイド
        %li
          FURIMAロゴ利用ガイドライン
        %li
          お知らせ

  .footer_img
    = image_tag "/material/logo/logo-white.png", class: "footer_img"
    .footer_img_content
      &copy;FURIMA
  
  .footer_camera
    = link_to new_product_path, class: "footer_camera_link" do
      出品する
      = image_tag "/material/icon/icon_camera.png", class: "footer_camera_icon"

app/views/products/new.html.haml
= render 'form', {product:@product}

app/views/products/show.html.haml
.show_header
  .show_header_search
    .show_header_search_logo
      = image_tag '/material/logo/logo.png', class: "show_header_search_logo"

.product
  .product_show
    .product_show_name
      = @product.name
    .product_show_main
      .product_show_images  
        = image_tag @product.images[0].image.url, class: "product_show_image active"
        - @product.images.each_with_index do |image, i|
          = image_tag image.image.url, data: {active: i}, class: "product_show_image"
      
      %table{class: 'product_show_lists'}
        %tr
          %th.product_show_list_nickname
            出品者
          %td
            = @user.nickname
        %tr
          %th.product_show_list_category
            カテゴリー
          %td
            = @product.category.name 
        %tr
          %th.product_show_list_brand
            ブランド
          %td
            = @product.brand.name
        %tr
          %th.product_show_list_size
            サイズ
          %td
            = @product.size.name
        %tr
          %th.product_show_list_status
            商品の状態
          %td
            = @product.status.name
        %tr
          %th.product_show_list_delivery
            配送料の負担
          %td
            = @product.delivery.name
        %tr
          %th.product_show_list_prefecture
            発送元の地域
          %td
            = @product.prefecture.name
        %tr
          %th.product_show_list_deliverytime
            配送日時
          %td
            = @product.deliverytime.name       
    .product_show_price
      ￥
      = @product.price
      %span
        (税込み)
      .product_show_price_delivery
        = @product.delivery.name
  .product_text
    .product_text_title
      %span
        商品概要
      .product_text_title_content
        = @product.text

  .product_buy
    - if user_signed_in? && @product.user_id == current_user.id      
      = link_to edit_product_path(@product.id), class: "product_buy_edit" do
        %span
          商品内容を編集する
    -else
      = link_to product_purchase_path(@product.id), class: "product_buy_edit" do
        .product_buy_yes
          商品購入画面に進む
      
.footer
  .footer_lists
    .footer_list
      .footer_list_title
        FURIMAについて
      %ul.footer_list_contents
        %li
          会社概要（運営会社）
        %li
          プライバシーポリシー
        %li
          FURIMA利用規約
        %li
          ポイントに関する特約
    
    .footer_list
      .footer_list_title
        FURIMAを見る
      %ul.footer_list_contents
        %li
          カテゴリー一覧
        %li
          ブランド一覧

    .footer_list
      .footer_list_title
        ヘルプ＆ガイド
      %ul.footer_list_contents
        %li
          FURIMAガイド
        %li
          FURIMAロゴ利用ガイドライン
        %li
          お知らせ

  .footer_img
    = image_tag "/material/logo/logo-white.png", class: "footer_img"
    .footer_img_content
      &copy;FURIMA